// src/App.tsx
import { useEffect, useRef, useState, useCallback } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { useGSAP } from '@gsap/react'
import SceneCanvas from './r3f/Canvas'
import Act1OceanVoyage from './acts/Act1OceanVoyage'
import Act2GridTransition from './acts/Act2GridTransition'
import Act3ContentPhase from './acts/Act3ContentPhase'
import { useScrollStore } from './stores/scrollStore'
import { WHITE_OUT_THRESHOLD, WHITE_OUT_END, GRID_START, GRID_SHIFT_START } from './r3f/ScrollRig'
import { getLighthouseCapture } from './actors/LighthouseCapture'
import './App.css'

gsap.registerPlugin(ScrollTrigger)

const SCROLL_VH = 15
const FRICTION = 0.955
const MAX_VELOCITY = 0.025

/**
 * App 根组件 — GSAP ScrollTrigger + 滚动物理 + DOM 叠加层。
 *
 * 原 App.vue 逻辑迁移：onWheel, onClick, ScrollTrigger, GSAP ticker。
 *
 * 援引：
 *   Codrops 2025 — GSAP ScrollTrigger + R3F 混合
 *   @gsap/react useGSAP — 自动 cleanup
 */
export default function App() {
  // ---- Zustand store ----
  const { scrollProgress, setScrollProgress } = useScrollStore()

  // ---- Physics state (refs — no re-render) ----
  const physRef = useRef({ target: 0, velocity: 0, lastScrollbar: 0, lastPhysics: 0, active: true })
  const clickTweenRef = useRef<gsap.core.Tween | null>(null)
  const focusTweenRef = useRef<gsap.core.Tween | null>(null)
  const lighthouseCapturedRef = useRef(false)
  const stRef = useRef<ScrollTrigger | null>(null)

  // ---- UI state (React — triggers re-render) ----
  const [hintVisible, setHintVisible] = useState(true)
  const [isClickPlaying, setIsClickPlaying] = useState(false)
  const [isAct3Focused, setIsAct3Focused] = useState(false)
  const [brandTextVisible, setBrandTextVisible] = useState(false)
  const [lighthouseImage, setLighthouseImage] = useState<string | null>(null)
  const overlayData = useScrollStore(s => s.overlayData)

  // ---- Act visibility ----
  const needsAct1 = (sp: number) => sp < GRID_START + 0.01
  const needsAct2 = (sp: number) => sp >= WHITE_OUT_THRESHOLD - 0.01 && sp < GRID_SHIFT_START + 0.01
  const needsAct3 = (sp: number) => sp >= GRID_SHIFT_START - 0.01

  // ---- syncScrollbar ----
  const syncScrollbar = useCallback(() => {
    const h = document.body.scrollHeight - window.innerHeight
    if (h > 0) window.scrollTo(0, physRef.current.target * h)
  }, [])

  // ---- ScrollTrigger (native scrollbar) ----
  useGSAP(() => {
    document.body.style.height = window.innerHeight * SCROLL_VH + 'px'

    stRef.current = ScrollTrigger.create({
      trigger: document.body,
      start: 'top top',
      end: 'bottom bottom',
      scrub: 0,
      onUpdate: (self) => {
        if (Math.abs(self.progress - physRef.current.target) < 0.0005) return
        physRef.current.lastScrollbar = performance.now()
        physRef.current.velocity = 0
        physRef.current.target = self.progress
        setScrollProgress(self.progress)
        if (self.progress > 0.02 && hintVisible) setHintVisible(false)
      },
    })

    return () => { stRef.current?.kill() }
  }, [])

  // ---- GSAP physics ticker ----
  useEffect(() => {
    const ticker = () => {
      const p = physRef.current
      if (!p.active) return
      const now = performance.now()
      if (!p.lastPhysics) { p.lastPhysics = now; return }
      const dt = Math.min(0.1, (now - p.lastPhysics) / 1000)
      p.lastPhysics = now
      const dtFrames = dt * 60

      if (now - p.lastScrollbar < 80) return
      if (isClickPlaying) return

      p.target += p.velocity * dtFrames
      if (p.target <= 0) { p.target = 0; p.velocity = 0 }
      if (p.target >= 1) { p.target = 1; p.velocity = 0 }

      p.velocity *= Math.pow(FRICTION, dtFrames)
      if (Math.abs(p.velocity) < 0.00001) p.velocity = 0

      setScrollProgress(p.target)
      syncScrollbar()
    }
    gsap.ticker.add(ticker)
    return () => { gsap.ticker.remove(ticker) }
  }, [isClickPlaying, syncScrollbar])

  // ---- wheel handler ----
  const onWheel = useCallback((e: WheelEvent) => {
    e.preventDefault()
    if (isAct3Focused) return
    if (isClickPlaying && clickTweenRef.current) {
      clickTweenRef.current.kill()
      clickTweenRef.current = null
      setIsClickPlaying(false)
    }
    const step = e.deltaY / (window.innerHeight * SCROLL_VH) * 0.65
    physRef.current.velocity += step
    physRef.current.velocity = Math.max(-MAX_VELOCITY, Math.min(MAX_VELOCITY, physRef.current.velocity))
  }, [isAct3Focused, isClickPlaying])

  // ---- click fast-forward ----
  const onClick = useCallback(() => {
    if (isClickPlaying) return
    if (scrollProgress >= 0.995) return
    setIsClickPlaying(true)
    physRef.current.velocity = 0

    const tweenObj = { val: physRef.current.target }
    clickTweenRef.current = gsap.to(tweenObj, {
      val: 1.0,
      duration: 2,
      ease: 'power2.inOut',
      onUpdate: () => {
        physRef.current.target = tweenObj.val
        setScrollProgress(tweenObj.val)
        syncScrollbar()
      },
      onComplete: () => {
        setIsClickPlaying(false)
        clickTweenRef.current = null
      },
    })
  }, [isClickPlaying, scrollProgress, setScrollProgress, syncScrollbar])

  // ---- event listeners ----
  useEffect(() => {
    window.addEventListener('wheel', onWheel, { passive: false })
    window.addEventListener('click', onClick)
    return () => {
      window.removeEventListener('wheel', onWheel)
      window.removeEventListener('click', onClick)
    }
  }, [onWheel, onClick])

  // ---- brand text visibility ----
  useEffect(() => {
    setBrandTextVisible(scrollProgress >= 0.70)
  }, [scrollProgress])

  // computeTextOffset — Act 3 grid shift 同步到品牌文字位移
  const textOffsetY = scrollProgress >= GRID_SHIFT_START
    ? Math.round(((scrollProgress - GRID_SHIFT_START) / (1.0 - GRID_SHIFT_START)) * 32 * 10) / 10
    : 0

  // ---- lighthouse screenshot ----
  useEffect(() => {
    if (scrollProgress >= 0.54 && !lighthouseCapturedRef.current) {
      lighthouseCapturedRef.current = true
      const captureFn = getLighthouseCapture()
      if (captureFn) {
        const img = captureFn()
        if (img) setLighthouseImage(img)
      }
    }
  }, [scrollProgress])

  // ---- cleanup ----
  useEffect(() => {
    return () => {
      physRef.current.active = false
      stRef.current?.kill()
      ScrollTrigger.getAll().forEach((t: ScrollTrigger) => t.kill())
      document.body.style.height = ''
    }
  }, [])

  const sp = scrollProgress

  return (
    <>
      <SceneCanvas>
        <Act1OceanVoyage visible={needsAct1(sp)} />
        <Act2GridTransition visible={needsAct2(sp)} />
        <Act3ContentPhase visible={needsAct3(sp)} />
      </SceneCanvas>

      {/* 滚动提示 */}
      {hintVisible && (
        <div className="scroll-hint" aria-hidden="true">
          <span>Scroll</span>
          <span className="click-hint">or click to skip</span>
          <div className="scroll-arrow" />
        </div>
      )}

      {/* 品牌文字 */}
      {brandTextVisible && (
        <div className="brand-text" aria-hidden="true"
          style={{ '--text-offset-y': `${textOffsetY}px` } as React.CSSProperties}>
          <div className="brand-text-row">
            {lighthouseImage && (
              <img src={lighthouseImage} alt="" className="brand-lighthouse-icon" />
            )}
            <div className="brand-text-inner">
              <p className="brand-line-1">Personal Site</p>
              <p className="brand-line-2">By YeQuDesu</p>
            </div>
          </div>
        </div>
      )}

      {/* 聚焦 SVG 叠加层 */}
      {overlayData.focused && (
        <svg className="focus-overlay" width="100%" height="100%">
          {overlayData.star && (
            <circle cx={overlayData.star.x} cy={overlayData.star.y} r={overlayData.star.r + 10}
              fill="none" stroke="#64748b" strokeWidth={1} strokeDasharray="4 6" className="overlay-ring" />
          )}
          {overlayData.planet && (
            <circle cx={overlayData.planet.x} cy={overlayData.planet.y} r={overlayData.planet.r + 8}
              fill="none" stroke="#64748b" strokeWidth={1} strokeDasharray="4 6" className="overlay-ring" />
          )}
          {overlayData.tangents?.map((t: any, i: number) => (
            <line key={i} x1={t.x1} y1={t.y1} x2={t.x2} y2={t.y2}
              stroke="#94a3b8" strokeWidth={0.5} className="overlay-line" />
          ))}
        </svg>
      )}

      {/* 页脚 */}
      <footer className="app-footer">
        <span>&copy; 2025 YeQuDesu · </span>
        <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener">
          闽ICP备2026019172号-1
        </a>
      </footer>
    </>
  )
}

// src/App.vue
<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import LighthouseScene from './components/LighthouseScene.vue'
import AppFooter from './components/AppFooter.vue'

gsap.registerPlugin(ScrollTrigger)

const SCROLL_VH = 15
const FRICTION = 0.955      // per-60fps-frame velocity decay
const MAX_VELOCITY = 0.025  // cap per-60fps-frame progress delta

// ---- physics state ----
let _physTarget = 0
let _physVelocity = 0
let _lastScrollbarTime = 0
let _lastPhysicsTime = 0
let _physActive = true

// ---- reactive state ----
const scrollProgress = ref(0)
const clickProgress = ref(0)
const isClickPlaying = ref(false)
const hintVisible = ref(true)
const lighthouseImage = ref(null)
const sceneRef = ref(null)
const brandTextRef = ref(null)
const brandTextVisible = computed(() => scrollProgress.value >= 0.70)
let _focusTween = null
const isAct3Focused = ref(false)
const overlayData = ref({ focused: false })
const effectiveProgress = computed(() =>
  isClickPlaying.value ? clickProgress.value : scrollProgress.value
)

function onOverlayData(data) {
  overlayData.value = data
}

// ---- helpers ----
function smoothstep(t) {
  return t * t * (3 - 2 * t)
}
function clamped(sp, s, e) {
  return Math.max(0, Math.min(1, (sp - s) / (e - s)))
}
function syncScrollbar() {
  const h = document.body.scrollHeight - window.innerHeight
  if (h > 0) window.scrollTo(0, _physTarget * h)
}

// ---- character visibility ----
const line1Opacity = computed(() => smoothstep(clamped(scrollProgress.value, 0.70, 0.82)))
const line2Opacity = computed(() => smoothstep(clamped(scrollProgress.value, 0.82, 0.92)))

// ---- click fast-forward ----
let _clickTween = null
function onClick() {
  if (isClickPlaying.value) return
  if (scrollProgress.value >= 0.995) return
  isClickPlaying.value = true
  _physVelocity = 0 // kill momentum

  const tweenObj = { val: _physTarget }
  _clickTween = gsap.to(tweenObj, {
    val: 1.0,
    duration: 2,
    ease: 'power2.inOut',
    onUpdate: () => {
      _physTarget = tweenObj.val
      scrollProgress.value = _physTarget
      clickProgress.value = _physTarget
      syncScrollbar()
    },
    onComplete: () => {
      isClickPlaying.value = false
      _clickTween = null
    }
  })
}

// ---- wheel handler (adds velocity for momentum) ----
function onWheel(e) {
  e.preventDefault()
  if (isAct3Focused.value) return  // block scroll during planet focus
  if (isClickPlaying.value && _clickTween) {
    _clickTween.kill()
    _clickTween = null
    isClickPlaying.value = false
  }
  const step = e.deltaY / (window.innerHeight * SCROLL_VH) * 0.65
  _physVelocity += step
  _physVelocity = Math.max(-MAX_VELOCITY, Math.min(MAX_VELOCITY, _physVelocity))
}

// ---- lighthouse capture ----
let _lighthouseCaptured = false
function ensureCapture() {
  if (_lighthouseCaptured) return
  if (!sceneRef.value) return
  if (scrollProgress.value >= 0.54) {
    _lighthouseCaptured = true
    try {
      const url = sceneRef.value.captureLighthouse()
      if (url) lighthouseImage.value = url
    } catch (e) {
      console.warn('Lighthouse capture failed:', e)
    }
  }
}

// ---- ScrollTrigger (native scrollbar → direct position) ----
let st
function onScrollTrigger(self) {
  // Ignore scroll events triggered by our own syncScrollbar (position unchanged)
  if (Math.abs(self.progress - _physTarget) < 0.0005) return

  _lastScrollbarTime = performance.now()
  _physVelocity = 0 // kill wheel momentum when user grabs scrollbar
  _physTarget = self.progress
  scrollProgress.value = _physTarget

  if (_physTarget > 0.02 && hintVisible.value) {
    hintVisible.value = false
  }
}

// ---- watch scrollProgress to drive capture ----
watch(scrollProgress, () => {
  ensureCapture()
})

// ---- act3 focus handler (GSAP-driven fade + slide) ----
function onFocusChange(focused) {
  isAct3Focused.value = focused
  const el = brandTextRef.value
  if (!el) return
  if (_focusTween) _focusTween.kill()
  _focusTween = gsap.to(el, {
    opacity: focused ? 0 : 1,
    marginTop: focused ? -24 : 0,
    duration: 0.5,
    ease: 'power2.out',
    overwrite: 'auto'
  })
}

onMounted(() => {
  document.body.style.height = window.innerHeight * SCROLL_VH + 'px'

  // ScrollTrigger: fires when native scroll changes (scrollbar drag etc)
  st = ScrollTrigger.create({
    trigger: document.body,
    start: 'top top',
    end: 'bottom bottom',
    scrub: 0,
    onUpdate: onScrollTrigger
  })

  // Physics ticker: applies velocity with friction (delta-time based)
  gsap.ticker.add(() => {
    if (!_physActive) return
    const now = performance.now()
    if (!_lastPhysicsTime) { _lastPhysicsTime = now; return }
    const dt = Math.min(0.1, (now - _lastPhysicsTime) / 1000) // seconds
    _lastPhysicsTime = now
    const dtFrames = dt * 60 // normalize to 60fps-equivalent

    // Skip if scrollbar was recently used (user is dragging it)
    if (now - _lastScrollbarTime < 80) return
    // Skip during click fast-forward (gsap tween controls position)
    if (isClickPlaying.value) return

    // Apply velocity (scaled by delta time)
    _physTarget += _physVelocity * dtFrames

    // Clamp & stop at bounds
    if (_physTarget <= 0) { _physTarget = 0; _physVelocity = 0 }
    if (_physTarget >= 1) { _physTarget = 1; _physVelocity = 0 }

    // Friction decay (delta-time normalized)
    _physVelocity *= Math.pow(FRICTION, dtFrames)
    if (Math.abs(_physVelocity) < 0.00001) _physVelocity = 0

    scrollProgress.value = _physTarget
    syncScrollbar()
  })

  window.addEventListener('click', onClick)
  window.addEventListener('wheel', onWheel, { passive: false })
})

onUnmounted(() => {
  _physActive = false
  st?.kill()
  ScrollTrigger.getAll().forEach((t) => t.kill())
  document.body.style.height = ''
  window.removeEventListener('click', onClick)
  window.removeEventListener('wheel', onWheel)
})
</script>

<template>
  <LighthouseScene ref="sceneRef" :scrollProgress="effectiveProgress" @focus-change="onFocusChange" @overlay-data="onOverlayData" />

  <!-- Focus overlay: SVG line art — tangent lines between star and planet -->
  <svg
    v-if="overlayData.focused"
    class="focus-overlay"
    width="100%" height="100%"
  >
    <!-- Star outline circle -->
    <circle
      :cx="overlayData.star.x" :cy="overlayData.star.y" :r="overlayData.star.r + 10"
      fill="none" stroke="#64748b" stroke-width="1" stroke-dasharray="4 6"
      class="overlay-ring"
    />
    <!-- Planet outline circle -->
    <circle
      :cx="overlayData.planet.x" :cy="overlayData.planet.y" :r="overlayData.planet.r + 8"
      fill="none" stroke="#64748b" stroke-width="1" stroke-dasharray="4 6"
      class="overlay-ring"
    />
    <!-- Tangent lines -->
    <line
      v-for="(t, i) in overlayData.tangents" :key="i"
      :x1="t.x1" :y1="t.y1" :x2="t.x2" :y2="t.y2"
      stroke="#94a3b8" stroke-width="0.5"
      class="overlay-line"
    />
  </svg>

  <Transition name="hint-fade">
    <div v-if="hintVisible" class="scroll-hint" aria-hidden="true">
      <span>Scroll</span>
      <span class="click-hint">or click to skip</span>
      <div class="scroll-arrow" />
    </div>
  </Transition>

  <div
    v-if="brandTextVisible"
    ref="brandTextRef"
    class="brand-text"
    :class="{ 'no-transition': isClickPlaying }"
    aria-hidden="true"
  >
    <div class="brand-text-row">
      <img
        v-if="lighthouseImage"
        :src="lighthouseImage"
        class="lighthouse-icon"
        :style="{ opacity: line1Opacity }"
        alt=""
      />
      <div class="brand-text-inner">
        <p class="brand-line-1" :style="{ opacity: line1Opacity }">Personal Site</p>
        <p class="brand-line-2" :style="{ opacity: line2Opacity }">By YeQuDesu</p>
      </div>
    </div>
  </div>

  <AppFooter />
</template>

<style>
/* ---- scroll hint ---- */
.scroll-hint {
  position: fixed;
  bottom: 2.8rem;
  left: 50%;
  transform: translateX(-50%);
  z-index: 5;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
  color: #aab;
  font-size: 0.68rem;
  letter-spacing: 0.15em;
  pointer-events: none;
}
.scroll-arrow {
  width: 20px;
  height: 20px;
  border-right: 1.5px solid #889;
  border-bottom: 1.5px solid #889;
  transform: rotate(45deg);
  opacity: 0.5;
  animation: sc-bounce 2s ease-in-out infinite;
}
.click-hint {
  font-size: 0.58rem;
  color: #778;
  opacity: 0.7;
  letter-spacing: 0.08em;
}
@keyframes sc-bounce {
  0%, 100% { transform: rotate(45deg) translateY(0); }
  50% { transform: rotate(45deg) translateY(6px); }
}
.hint-fade-enter-active { transition: opacity 0.8s; }
.hint-fade-leave-active { transition: opacity 0.4s; }
.hint-fade-enter-from,
.hint-fade-leave-to { opacity: 0; }

/* ---- brand text ---- */
.brand-text {
  position: fixed;
  inset: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
  transform: translateY(calc(var(--text-offset-y, 0px) - 4vh));
}
.brand-text.no-transition,
.brand-text.no-transition * {
  transition: none !important;
}
.brand-text-row {
  display: flex;
  align-items: flex-end;
  gap: 0em;
}
.brand-text-inner {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 0.05rem;
  margin-left: 0.15em;
}
.brand-line-1 {
  margin: 0;
  margin-right: -0.05em; /* cancel trailing letter-spacing */
  font-family: 'Georgia', 'Times New Roman', serif;
  font-size: clamp(1.8rem, 4.5vw, 3.5rem);
  font-weight: 600;
  color: #222;
  letter-spacing: 0.05em;
  white-space: nowrap;
  text-align: left;
}
.brand-line-2 {
  margin: 0;
  margin-right: -0.04em; /* cancel trailing letter-spacing */
  font-family: 'Georgia', 'Times New Roman', serif;
  font-size: clamp(0.55rem, 1.0vw, 0.75rem);
  font-weight: 400;
  color: #888;
  letter-spacing: 0.04em;
  font-style: italic;
  text-align: left;
}
/* ---- focus overlay SVG ---- */
.focus-overlay {
  position: fixed;
  inset: 0;
  z-index: 5;
  pointer-events: none;
}
.overlay-ring {
  animation: ring-in 0.6s ease-out both;
}
@keyframes ring-in {
  from { opacity: 0; stroke-dashoffset: 30; }
  to   { opacity: 1; stroke-dashoffset: 0; }
}
.overlay-line {
  animation: line-in 0.8s ease-out 0.2s both;
}
@keyframes line-in {
  from { opacity: 0; stroke-dashoffset: 20; }
  to   { opacity: 1; stroke-dashoffset: 0; }
}

.lighthouse-icon {
  font-size: clamp(1.8rem, 4.5vw, 3.5rem);
  height: 2.8em;
  width: auto;
  margin-bottom: -0.08em;
  vertical-align: baseline;
  object-fit: contain;
  transform: translateY(-6px);
}
</style>
